### ISSUE TITLE
Split utils.py in meaningful units

### ISSUE THREAD

**Issue by GregoireUhlrich** [aureliencarle/cryptext#5]
The content of the `utils.py` is actually composed of two main utilities that could deserve their own file.

- The **encryption / decryption** utilities that can be moved into a `encryption.py` file
- The **I/O** utilities for the interpreter that could be moved in a `cryptext_io.py` file for example.

Also, the I/O utilities in the actual `Utils` class could be simple methods as there is no associated state.

**Comment by aureliencarle** [comment]
half of the job

**Comment by aureliencarle** [comment]
see PR #11
