### ISSUE TITLE
Linux command like

### ISSUE THREAD

**Issue by aureliencarle** [aureliencarle/cryptext#8]
Why not transform commands to be more close to bash commands ... 
Example : create => touch
                 show => cat ??

**Comment by GregoireUhlrich** [comment]
Not a bad id

**Comment by GregoireUhlrich** [comment]
- ls: show sessions or passwords if inside a session (maybe rename session -> Directory ?)
 - rm: remove a password (or session if rm -r)
 - touch: create a password (rename to File ?)
 - mkdir: create a session
 - cat: shows password
 - exit: quit cryptext

**Comment by aureliencarle** [comment]
exit already exist

**Comment by aureliencarle** [comment]
See PR #12
